services:
  frontend:
    image: "ml-kurkkumopo-frontend"
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    image: "ml-kurkkumopo-backend"
    build: ./ml-kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    depends_on:
      - training

  training:
    image: "ml-kurkkumopo-training"
    build: ./ml-kurkkumopo-training
    volumes:
      - ./ml-kurkkumopo-training/imgs:/src/imgs
      - model:/src/model

volumes:
  model:

