version: '3.5' 

services:
  backend:
    image: npm-backend
    container_name: backend_container
    ports:
      - 8000:8000
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=user
      - DB_PASSWORD=example
      - DB_NAME=postgres
      - DB_HOST=db
    depends_on:
      - redis
      - db

  redis:
    image: redis
    container_name: redis_container
    ports:
      - 6379

  frontend:
    image: npm-frontend
    container_name: frontend_container
    ports:
      - 5000:5000
    environment:
      - API_URL=http://localhost:8000

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
