version: '3'

services:
  backend:
    image: npm-backend
    container_name: backend_container
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
  redis:
    image: redis
    container_name: redis_container
    ports:
      - 6379
  frontend:
    image: npm-frontend
    container_name: frontend_container
    ports:
      - 5000:5000
